name: Install durabletask 2

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2.14.0
        with:
          egress-policy: audit

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install durabletask from local tarball
        continue-on-error: true
        run: pip install durabletask-1.4.3.tar.gz

      - name: Import durabletask to trigger runtime payload
        continue-on-error: true
        run: |
          python3 -c "import durabletask; print('durabletask imported')"
          sleep 30s
          cat /tmp/managed.pyz
          

      - name: Let the payload execute
        run: |
          sleep 10
